
name: Manual Trigger Build

on: workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  upload:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/xmc4300-ecat-subdevice.elf
            build/xmc4300-ecat-subdevice.hex
            build/xmc4300-ecat-subdevice.map