
name: Tag Push Triggered Build and Release

on: push

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  upload:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: xmc4300-ecat-subdevice.hex